export default `
<p>Estes Termos de Uso aplicam-se exclusivamente ao seu acesso e uso da Ferramenta de Gestão e Governança Elinor e todos os dados subjacentes, sites associados, serviços online e aplicativos móveis (coletivamente, a "Ferramenta" ou "Elinor") disponibilizados pelo World Wildlife Fund, Inc. ("WWF") através do site <a href="https://elinordata.org">elinordata.org</a> (o "Site"). Ao acessar ou usar a Ferramenta e/ou o Site, você concorda em estar vinculado por estes Termos de Uso e reconhece que estes Termos de Uso não alteram de forma alguma os termos ou condições de qualquer outro acordo que você possa ter com o WWF. Se você estiver usando a Ferramenta ou o Site em nome de uma entidade, você declara e garante que está autorizado a aceitar estes Termos de Uso em nome dessa entidade, e que tal entidade concorda em indenizar o WWF por violações destes Termos de Uso.</p>
<p>O WWF reserva-se o direito de alterar ou modificar quaisquer termos e condições contidos nestes Termos de Uso a qualquer momento e a seu exclusivo critério. Quaisquer alterações ou modificações serão efetivas imediatamente após a postagem das revisões no Site. Seu uso contínuo da Ferramenta após a postagem de alterações ou modificações constituirá sua aceitação de tais alterações ou modificações. Portanto, você deve revisar frequentemente os Termos de Uso e as políticas aplicáveis de tempos em tempos para entender os termos e condições que se aplicam ao seu uso da Ferramenta. Se você não concordar com os termos alterados, você deve parar de usar a Ferramenta.</p>
<p>Os Termos de Uso aplicáveis à Ferramenta são os seguintes:</p>
<ul>
   <li><strong>Uso.</strong> Você concorda em usar a Ferramenta, ou "Elinor" e quaisquer produtos gerados usando dados da Elinor para avançar os objetivos de conservação. Você concorda em usar a Ferramenta e o Site em conformidade com todas as leis, regras, estatutos e regulamentos aplicáveis. Você reconhece e concorda que é o único responsável por tal conformidade e concorda em indenizar o WWF e seus diretores, oficiais, funcionários, agentes e parceiros contra qualquer responsabilidade decorrente de uma violação de suas obrigações de conformidade. Você concorda ainda em não usar a Ferramenta ou o Site de forma alguma para difamar, assediar ou ameaçar qualquer indivíduo ou entidade, ou para carregar ou disponibilizar qualquer material que seja obsceno, pornográfico ou ofensivo, intencionalmente enganoso, discriminatório ou abusivo para qualquer indivíduo ou grupo, viole a lei aplicável ou promova qualquer violação dessa lei, contenha ou instale qualquer malware, vírus ou outros componentes prejudiciais, ou infrinja o direito proprietário ou pessoal de terceiros. Embora o WWF possa, a seu critério, remover qualquer conteúdo que acredite estar em violação da lei ou das políticas do WWF, o WWF não faz representações quanto à sua moderação e não se compromete a revisar todo o conteúdo carregado na plataforma<br /></li>
   <li><strong>Conta; Informações Pessoais; Controlando Suas Informações.</strong> Se você deseja carregar conteúdo na Elinor, você deve primeiro registrar-se para uma conta através do Site. O registro requer a criação de um login protegido por senha e fornecimento de informações pessoais mínimas, incluindo seu nome e endereço de email. Você é responsável pela segurança de seu login e senha e por todo o conteúdo fornecido, perfis criados, avaliações implementadas e qualquer outra atividade ocorrendo sob eles. Você notificará prontamente o WWF caso tome conhecimento de qualquer uso ou acesso não autorizado ou suspeito ao Serviço. Não usaremos as informações pessoais que você fornecer para qualquer finalidade que não seja administrar sua conta no Site e contatá-lo em relação a mudanças significativas ou interrupções na plataforma. Você tem o direito de solicitar que quaisquer informações pessoais coletadas através do uso da Ferramenta e do Site sejam alteradas ou excluídas em um momento posterior <strong>Se você tiver perguntas sobre as informações pessoais coletadas, incluindo pedidos de exclusão, por favor contate help@elinordata.org.</strong> Enquanto o WWF não divulgará suas informações pessoais a terceiros, exceto para o propósito de ajudar a administrar a Ferramenta e o Site, se você for um residente da Califórnia, a Seção 1798.83 do Código Civil da Califórnia permite que você solicite informações sobre nossa divulgação de suas informações pessoais a terceiros para fins de marketing direto desses terceiros.<strong> Para fazer tal solicitação, por favor contate help@elinordata.org.</strong> Observe que o WWF pode não ser sempre capaz de cumprir com pedidos de exclusão se legalmente impedido de fazê-lo, mas a organização, na medida do permitido, notificará você sobre tais restrições em resposta ao seu pedido.</li>
</ul>
<ul>
    <li>
    <strong>Direitos Autorais e Licença Limitada.</strong> A menos que indicado de outra forma na Ferramenta e/ou no Site, a Ferramenta, o Site e todo o conteúdo e outros materiais contidos neles, incluindo, sem limitação, todas as marcas comerciais, marcas de serviço, designs, textos, gráficos, imagens, informações, dados, software, métodos, invenções, arquivos de som, outros arquivos e a seleção e arranjo dos mesmos são propriedade proprietária do WWF e estão protegidos pelas leis de direitos autorais, marcas comerciais e outras leis de propriedade intelectual dos EUA e internacionais. É concedida permissão para acessar e usar a Ferramenta e o Site exclusivamente para o propósito não comercial descrito acima e de acordo com estes Termos de Uso. Qualquer uso por você de qualquer nome, logo ou outra marca da Elinor estará sujeito ao consentimento prévio por escrito do WWF. Você concorda expressamente que a permissão para usar a Ferramenta/Site não inclui: (a) qualquer uso comercial ou qualquer revenda ou redistribuição da Ferramenta ou do Site; (b) a coleta e uso de quaisquer listagens de produtos, imagens ou descrições; (c) a distribuição, desempenho público ou exibição pública de quaisquer materiais dentro da Ferramenta ou do Site, (d) fazer quaisquer usos derivados da Ferramenta ou do Site, ou qualquer parte deles; (e) uso de quaisquer métodos de mineração de dados, robôs ou métodos similares de coleta ou extração de dados; (f) download (exceto o cache de página ou conforme expressamente permitido) de qualquer parte da Ferramenta ou do Site; ou (g) qualquer uso da Ferramenta ou do Site que não seja para seu propósito pretendido. A permissão concedida aqui é revogável pelo WWF a qualquer momento, com ou sem causa. Exceto conforme expressamente indicado aqui, a Ferramenta, o Site e os materiais subjacentes contidos neles não podem ser copiados, reproduzidos, distribuídos, republicados, baixados, exibidos, postados, transmitidos ou usados de qualquer forma ou por qualquer meio, incluindo, mas não limitado a, eletrônico, mecânico, fotocópia, gravação ou outros, sem a permissão prévia por escrito do WWF ou do proprietário dos direitos autorais. A permissão dada a você termina automaticamente se você violar qualquer um dos Termos de Uso. Após a rescisão, você deve imediatamente destruir quaisquer materiais baixados e impressos. Você também não pode, sem a permissão do WWF, "espelhar" qualquer material contido na Ferramenta ou no Site em qualquer outro servidor. Qualquer uso não autorizado de qualquer material contido na Ferramenta ou no Site pode violar a lei aplicável (incluindo leis de direitos autorais, leis de marcas comerciais, leis de privacidade e publicidade e regulamentos e estatutos de comunicações).
    </li>
</ul>
<ul>
   <li><strong>Conteúdo do Usuário. </strong>Você declara e garante que possui todo o conteúdo (incluindo dados fornecidos na avaliação) que você carrega, fornece ou de outra forma disponibiliza na Ferramenta ou no Site, e/ou possui todos os direitos no conteúdo necessário para consentir este Acordo, e que nenhuma parte do conteúdo infringirá ou violará qualquer direito autoral, segredo comercial, marca registrada, patente, invenção ou outro direito proprietário ou pessoal de terceiros. Você declara e garante que tal conteúdo será verdadeiro, preciso e completo ao melhor de seu conhecimento. Você é o único responsável por todo o seu conteúdo. Você concede ao WWF o direito perpétuo, livre de royalties, não exclusivo, irrevogável, mundial, mas não a obrigação, de usar, compartilhar, copiar e armazenar seu conteúdo em perpetuidade. O conteúdo que você possui e carrega permanecerá sua propriedade e não será compartilhado ou liberado pelo WWF sem sua permissão explícita, exceto que o WWF pode compartilhar seu conteúdo de forma agregada/anonimizada ou de outra forma, conforme permitido nas disposições de Compartilhamento de Dados abaixo. Observe, no entanto, que podemos não ser sempre capazes de cumprir com seu pedido de exclusão por razões legais específicas, que serão notificadas a você, se aplicável, no momento do seu pedido. Pedidos para excluir dados não pessoalmente identificáveis devem ser feitos por escrito ao operador.<br /> <br /> </li>
   <li><strong>Sites Vinculados ao Site. </strong>A Ferramenta e/ou o Site podem conter links para ou podem enquadrar sites de terceiros ("Sites de Terceiros") e podem conter ou vincular a informações, materiais, comunicações ou outro conteúdo de terceiros (coletivamente, o "Conteúdo de Terceiros"). Tal Conteúdo de Terceiros e Sites de Terceiros não estão sob o controle do WWF, e o WWF não endossa, assume qualquer responsabilidade ou obrigação por, ou faz quaisquer representações ou garantias em relação aos Sites de Terceiros, ao Conteúdo de Terceiros ou a quaisquer produtos ou serviços oferecidos por terceiros no Site ou em qualquer Site de Terceiros. O WWF não pretende que os links neste Site sejam referências ou endossos das entidades vinculadas, ou de seus produtos ou serviços, e são fornecidos para conveniência apenas. Seu uso de Sites de Terceiros ou Conteúdo de Terceiros, ou quaisquer produtos e serviços de terceiros, é por sua conta e risco e sujeito aos termos e condições do provedor.<br /> </li>
   <li>
      <strong>Reclamações de Direitos Autorais.</strong> Se você acredita de boa fé que sua obra protegida por direitos autorais foi reproduzida em nosso site sem autorização de uma forma que constitua violação de direitos autorais, por favor, forneça ao agente de direitos autorais do WWF, no endereço fornecido abaixo, as seguintes informações:
      <ol>
         <li>uma assinatura eletrônica ou física da pessoa autorizada a agir em nome do proprietário dos direitos autorais ou outro interesse de propriedade intelectual;</li>
         <li>uma descrição da obra protegida por direitos autorais ou outra propriedade intelectual que você alega ter sido infringida;</li>
         <li>uma descrição de onde o material que você alega estar infringindo está localizado neste site;</li>
         <li>seu endereço, número de telefone e endereço de email;</li>
         <li>uma declaração sua de que você acredita de boa fé que o uso contestado não é autorizado pelo proprietário dos direitos autorais, seu agente ou pela lei; e</li>
         <li>uma declaração sua, feita sob pena de perjúrio, de que as informações acima em sua notificação são precisas e que você é o proprietário dos direitos autorais ou da propriedade intelectual ou está autorizado a agir em nome do proprietário dos direitos autorais ou da propriedade intelectual.</li>
      </ol>
   </li>
</ul>

<p>O agente do WWF para notificação de reivindicações de violação de direitos autorais ou outra propriedade intelectual pode ser contatado por correio para Copyright Agent, c/o General Counsel, World Wildlife Fund, Inc., 1250 24th Street, N.W., Washington, DC, 20037; ou por email para copyrightagent@wwfus.org. Esta informação de contato é apenas para notificações suspeitas de violação de direitos autorais ou outras infrações de propriedade intelectual e não é para pedidos de reimpressão ou uso. Informações de contato para outros assuntos são fornecidas em outros lugares no Site. Podemos dar aviso de uma reivindicação de violação de direitos autorais aos nossos usuários por meio de um aviso geral no Site ou na Ferramenta, correio eletrônico para o endereço de email de um usuário em nossos registros ou por comunicação escrita.</p>

<ul>
   <li>
      <strong>Compartilhamento de Dados. </strong>O WWF oferece duas opções de privacidade com relação ao conteúdo que você carrega no Site ou na Ferramenta.
      <ul>
         <li><em>Privado</em>. Os resultados da avaliação (respostas quantitativas e qualitativas) são privados, assim como as informações fornecidas na caixa de Informações de Fundo, incluindo nome do facilitador, localização do site, nome da MA, tipo de gestão e governança e método de avaliação, são privados.</li>
         <li>Os resultados da avaliação (respostas quantitativas e qualitativas) são públicos, assim como as informações fornecidas na caixa de Informações de Fundo, incluindo nome do facilitador, localização do site, nome da MA, e tipo de gestão e governança e método de avaliação. Dados adicionais carregados, como planos de gestão e arquivos geoespaciais para facilitar a gestão do conhecimento também são públicos. <br /> Para manter a transparência sobre quem coletou os dados originais, os dados são sempre associados aos nomes de, e um mecanismo para contatar, os administradores do projeto (mas endereços de email nunca são públicos)</li>
      </ul>
   </li>
</ul>
<ul>
   <li><strong>Garantia e Isenções de Responsabilidade.</strong> A Ferramenta e o Site são fornecidos pelo WWF sob este Acordo exclusivamente para fins educacionais e em prol da missão isenta do WWF. A Ferramenta, o Site e todos os materiais, conteúdos, dados e outras informações contidos neles são fornecidos estritamente em uma base "como está" e "conforme disponível" sem garantia de qualquer tipo, expressa, implícita, estatutária ou de outra forma, incluindo, mas não limitado a, as garantias implícitas de título, não violação, comercialização ou adequação a um propósito específico. Na máxima extensão permitida por lei, o WWF não terá nenhuma responsabilidade relacionada a qualquer conteúdo decorrente de direitos de propriedade intelectual, difamação, privacidade, publicidade, obscenidade ou outras leis. O WWF também isenta de toda responsabilidade com relação ao uso indevido, perda, modificação ou indisponibilidade de quaisquer dados. O WWF não garante que a Ferramenta ou o Site atendam às suas necessidades; que a Ferramenta ou o Site serão ininterruptos, pontuais, seguros ou livres de erros; que as informações fornecidas através da Ferramenta ou do Site são precisas, confiáveis ou corretas; que quaisquer defeitos ou erros serão corrigidos; que a Ferramenta ou o Site estarão disponíveis em qualquer horário ou local específico; ou que a Ferramenta ou o Site estão livres de vírus ou outros componentes prejudiciais. O WWF não faz nenhuma representação de que a Ferramenta ou o Site são apropriados ou disponíveis para uso em todos os locais, e o acesso ao serviço de territórios onde o serviço é ilegal é proibido.<br /> </li>
   <li>
      <strong>Limitação de Responsabilidade</strong>. Em nenhuma circunstância o WWF, ou qualquer um de seus diretores, curadores, oficiais, funcionários, contratados independentes ou agentes da entidade operadora será responsável perante você ou qualquer terceiro por quaisquer danos especiais, punitivos, incidentais, indiretos ou consequenciais ou perdas de qualquer tipo, ou quaisquer danos ou perdas, incluindo aqueles resultantes da perda de uso, dados ou lucros, seja ou não previsível ou se o provedor de serviços foi avisado da possibilidade de tais danos ou perdas, e em qualquer teoria de responsabilidade, incluindo violação de contrato ou garantia, negligência ou outra ação tortuosa, ou qualquer outra reclamação decorrente ou relacionada ao:
      <ul>
         <li>O acesso ou uso ou a incapacidade de acessar ou usar a Ferramenta ou o Site;</li>
         <li>as declarações ou ações de qualquer terceiro no ou através da Ferramenta ou do Site;</li>
         <li>qualquer acesso ou alteração não autorizado à Ferramenta ou ao Site;</li>
         <li>qualquer informação que é enviada ou recebida ou não enviada ou recebida;</li>
         <li>qualquer falha em armazenar ou perda de dados ou outros conteúdos; e</li>
         <li>qualquer acesso ou interrupção atrasada ou interrompida ao Site ou à Ferramenta.<br /> </li>
      </ul>
   </li>
   <li><strong>Liberação e Indenização. </strong>Você concorda em liberar o WWF de quaisquer e todas as reivindicações, demandas e danos (reais e consequentes) de todo tipo e natureza, conhecidos e desconhecidos, decorrentes ou de qualquer forma relacionados ao seu acesso ou uso da Ferramenta ou do Site. Na máxima extensão permitida por lei, você concorda em indenizar, defender e isentar o WWF e todos os seus diretores, curadores, oficiais, funcionários, contratados independentes e agentes da entidade prestadora de serviços de quaisquer reivindicações de terceiros, incluindo honorários advocatícios razoáveis, devidos ou decorrentes de: (a) seu acesso ou uso da Ferramenta ou do Site; (b) sua violação de qualquer disposição deste Acordo; (c) conteúdo que você possa submeter, postar ou transmitir à Ferramenta ou ao Site (incluindo o uso de tal conteúdo por terceiros (por exemplo, dependência da precisão, completude ou utilidade de seus dados)); (d) conteúdo que você possa acessar ou usar usando a Ferramenta ou o Site, incluindo sua dependência na precisão, completude ou utilidade de quaisquer dados; ou (d) sua infração de qualquer direito de terceiros de propriedade autoral, marca registrada ou outro direito proprietário, violação de direito de privacidade ou publicidade, e difamação ou violação de qualquer outra lei em conexão com este Acordo.</li>
</ul>

<ul>
   <li><strong>Geral.</strong>
      <ul>
         <li><strong>Escolha de Lei. </strong>Exceto na medida em que a lei aplicável disponha de outra forma, este Acordo e qualquer acesso ou uso da Ferramenta e/ou do Site são regidos pelas leis do Distrito de Columbia, EUA. Você concorda e, por meio deste, se submete à jurisdição pessoal exclusiva e ao local dos tribunais localizados no Distrito de Columbia. Não obstante o exposto, o WWF reserva-se o direito de buscar medidas cautelares ou equitativas em qualquer jurisdição do mundo.</li>
         <li>As disposições deste Acordo que pela sua natureza devem sobreviver à rescisão irão sobreviver à rescisão, incluindo, sem limitação, disposições de propriedade, isenções de garantia, indenizações e limitações de responsabilidade.</li>
         <li>Na máxima extensão permitida por lei, você (1) concorda em receber comunicações do WWF em forma eletrônica através do endereço de email que você submeteu ou através da Ferramenta ou do Site; e (2) concorda que todos os Termos de Uso, acordos, avisos, divulgações e outras comunicações que o WWF forneça a você eletronicamente satisfazem qualquer requisito legal que essas comunicações satisfariam se fossem em papel. Notificações legais ao WWF devem ser feitas por escrito para o endereço fornecido abaixo.</li>
         <li>O WWF pode, a seu exclusivo critério, modificar todas ou quaisquer partes deste Acordo a qualquer momento. O WWF notificará você de quaisquer mudanças postando aviso de tais modificações na Ferramenta ou no Site, enviando aviso por e-mail ou outros meios, a critério do WWF. Seu uso continuado da Ferramenta e/ou do Site após o aviso de tais modificações será considerado como sua aceitação de tais modificações no Acordo.</li>
         <li><strong>Encerramento do Serviço ou Acesso</strong>. O WWF reserva-se o direito a qualquer momento e de tempos em tempos de modificar ou descontinuar, temporária ou permanentemente, a Ferramenta e/ou o Site, no todo ou em parte, ou seu acesso a eles, com ou sem aviso. Você pode encerrar seu acesso à Ferramenta/ao Site a qualquer momento seguindo o processo estabelecido na Ferramenta/no Site ou contatando o WWF. Você terá a escolha de remover ou reter quaisquer dados que você tenha carregado após o encerramento de sua conta.&nbsp; Após o encerramento, quaisquer licenças, direitos ou permissões concedidas a você aqui serão encerradas imediatamente.</li>
         <li><strong>Sem Cessão.</strong> Você não pode ceder ou delegar quaisquer direitos ou obrigações aqui sem o consentimento prévio por escrito do WWF, e qualquer cessão e delegação não autorizada por você será nula e sem efeito.</li>
         <li><strong>Severabilidade, Não Renúncia e Sobrevivência. </strong>Se qualquer parte deste Acordo for considerada inválida ou inaplicável, essa parte do Acordo será interpretada para refletir a intenção original das partes. As demais partes permanecerão em pleno vigor e efeito. Qualquer falha por parte do WWF em fazer cumprir qualquer disposição deste Acordo não será considerada uma renúncia do direito do WWF de fazer cumprir tal disposição. Os direitos do WWF sob este Acordo sobreviverão a qualquer rescisão ou expiração deste Acordo.</li>
         <li>Os títulos das seções neste Acordo são apenas para conveniência.</li>
         <li><strong>Acordo Integral.</strong> Este Acordo constitui o acordo integral entre você e o WWF relacionado ao assunto e substitui todos os entendimentos, comunicações ou acordos anteriores ou contemporâneos, escritos ou orais, sobre tal assunto.</li>
         <li>Se você tiver dúvidas sobre este Acordo, por favor contate help@elinordata.org. Envie notificações legais para: World Wildlife Fund, 1250 24th Street, N.W.Washington, DC 20037.</li>
      </ul>
   </li>
</ul>

`;
