export default `
<p>These Terms of Use apply exclusively to your access to, and use of, the Elinor Management and Governance Tool and all underlying data, associated websites, online services, and mobile applications (collectively, the &ldquo;Tool&rdquo; or &ldquo;Elinor&rdquo;) being made available by World Wildlife Fund, Inc. (&ldquo;WWF&rdquo;) through the website <a href="https://elinordata.org">elinordata.org</a> (the &ldquo;Site&rdquo;). By accessing or using the Tool and/or the Site, you agree to be bound by these Terms of Use and acknowledge that these Terms of Use do not alter in any way the terms or conditions of any other agreement you may have with WWF. If you are using the Tool or the Site on behalf of an entity, you represent and warrant that you are authorized to accept these Terms of Use on such entity's behalf, and that such entity agrees to indemnify WWF for violations of these Terms of Use.</p>
<p>WWF reserves the right to change or modify any of the terms and conditions contained in these Terms of Use at any time and in its sole discretion. Any changes or modifications will be effective immediately upon posting the revisions on the Site. Your continued use of the Tool following the posting of changes or modifications will constitute your acceptance of such changes or modifications. Therefore, you should frequently review the Terms of Use and applicable policies from time to time to understand the terms and conditions that apply to your use of the Tool. If you do not agree to the amended terms, you must stop using the Tool.</p>
<p>The Terms of Use applicable to the Tool are as follows:</p>
<ul>
   <li><strong>Usage.</strong>You agree to use the Tool, or &ldquo;Elinor&rdquo; and any products generated using data from Elinor to advance conservation goals. You agree to at all times use the Tool and the Site in compliance with all applicable laws, rules, statutes and regulations. You acknowledge and agree that you are solely responsible for such compliance and agree to indemnify WWF and its directors, officer, employees, agents, and partners against any liability arising as a result of a breach of your compliance obligations. You further agree not to use the Tool or the Site in any way to defame, harass or threaten any individual or entity, or to upload or otherwise make available any material that is obscene, pornographic or offensive, intentionally deceptive, discriminatory or abusive toward any individual or group, violates applicable law or promotes any such violation, contains or installs any malware, viruses or other harmful components, or infringes the proprietary or personal right of any third party. While WWF may in its discretion remove any content it believes is in violation of law or WWF's policies, WWF makes no representations as to its moderation and does not commit to review all content uploaded to the platform<br /> </li>
   <li><strong>Account; Personal Information; Controlling Your Information. </strong>If you wish to upload content to Elinor, you must first register for an account through the Site. Registration requires creating a password-protected login and providing minimal personal information, including your name and email address. You are responsible for the security of your login and password, and for all content provided, profiles created, assessments implemented and any other activity occurring thereunder. You will promptly notify WWF if you become aware of any actual or suspected unauthorized use of or access to the Service. We will not use the personal information you provide for any purpose other than to administer your Site account and to contact you regarding significant changes or disruptions to the platform. You have the right to ask for any personal information collected through use of the Tool and the Site to be changed or deleted at any later time <strong>If you have questions about the personal information collected, including requests for deletion, please contact help@elinordata.org.</strong> While WWF will not disclose your personal information to any third parties other than for the purpose of helping to administer the Tool and the Site, if you are a California resident, California Civil Code Section 1798.83 permits you to request information about our disclosure of your personal information to third parties for those parties&rsquo; own direct marketing purposes.<strong> To make such a request, please contact help@elinordata.org.</strong> Note that WWF may not always be able to comply with erasure requests if otherwise legally constrained from doing so, but the organization will, to the extent permitted, notify you of such constraints in response to your request.</li>
</ul>
<ul>
    <li>
    <strong>Copyright and Limited License.</strong> Unless otherwise indicated in the Tool and/or Site, the Tool, the Site, and all content and other materials contained therein, including, without limitation all trademarks, service marks, designs, texts, graphics, pictures, information, data, software, methods, inventions, sound files, other files and the selection and arrangement thereof are the proprietary property of WWF and are protected by U.S. and international copyright, trademark, and other intellectual property laws. Permission is granted to access and use the Tool and the Site solely for the non-commercial purpose described above and in accordance with these Terms of Use. Any use by you of any Elinor name, logo or other mark shall be subject to WWF&rsquo;s advance written consent. You expressly agree that permission to use the Tool/Site does not include: (a) any commercial use or any resale or redistribution of the Tool or the Site; (b) the collection and use of any product listings, pictures or descriptions; (c) the distribution, public performance or public display of any materials within the Tool or the Site, (d) making any derivative uses of the Tool or the Site, or any portion thereof; (e) use of any data mining, robots or similar data gathering or extraction methods; (f) downloading (other than the page caching or as otherwise expressly permitted) of any portion of the Tool or the Site; or (g) any use of the Tool or the Site other than for its intended purpose. The permission granted herein is revocable by WWF at any time, with or without cause. Except as expressly stated herein, the Tool, the Site, and the underlying materials contained therein may not be copied, reproduced, distributed, republished, downloaded, displayed, posted, transmitted or otherwise used in any form or by any means, including, but not limited to, electronic, mechanical, photocopying, recording, or otherwise, without the prior written permission of WWF or the copyright owner. The permission given to you terminates automatically if you breach any of the Terms of Use. Upon termination, you must immediately destroy any downloaded and printed materials. You also may not, without WWF's permission, "mirror" any material contained in the Tool or the Site on any other server. Any unauthorized use of any material contained in the Tool or the Site may violate applicable law (including copyright laws, trademark laws, the laws of privacy and publicity, and communications regulations and statutes).
    </li>
</ul>
<ul>
   <li><strong>User Content. </strong>You represent and warrant that you own all content (including data provided in the assessment) you upload, provide to, or otherwise make available on the Tool or the Site, and/or possess all rights in the content necessary to consent to this Agreement, and that no part of the content will infringe or violate any copyright, trade secret, trademark, patent, invention, or other proprietary or personal right of any third party. You represent and warrant that such content will be true, accurate, and complete to the best of your knowledge. You are solely responsible for all your content. You hereby grant to WWF the perpetual, royalty-free, nonexclusive, irrevocable, worldwide right, but not the obligation, to use, share, copy and store your content in perpetuity.&nbsp; Content that you own and upload will remain your property and will not be shared or released by WWF without your explicit permission, except that WWF may share your content on an aggregated/anonymized basis or otherwise as permitted under the Data Sharing provisions below. Note, however, that we may not always be able to comply with your request of erasure for specific legal reasons which will be notified to you, if applicable, at the time of your request. Requests to delete non personally identifiable data must be made in writing to the operator.<br /> <br /> </li>
   <li><strong>Sites Linked From the Site. </strong>The Tool and/or the Site may contain links to or may frame third party Web sites ("Third Party Sites") and may contain or link to third party information, materials, communications or other content (collectively the "Third Party Content"). Such Third Party Content and Third Party Sites are not under WWF's control, and WWF does not endorse, assume any responsibility or liability for, or make any representations or warranties regarding, the Third Party Sites, the Third Party Content or any products or services offered by any third parties on the Site or any Third Party Site. WWF does not intend links on this Site to be referrals or endorsements of the linked entities, or their products or services, and are provided for convenience only. Your use of Third Party Sites or Third Party Content, or any third party products and services, is at your own risk and subject to the terms and conditions or the provider.<br /> </li>
   <li>
      <strong>Copyright Complaints.</strong> If you believe in good faith that your copyrighted work has been reproduced on our site without authorization in a way that constitutes copyright infringement, please provide WWF&rsquo;s copyright agent, at the address provided below, the following information:
      <ol>
         <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</li>
         <li>a description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
         <li>a description of where the material that you claim is infringing is located on this site;</li>
         <li>your address, telephone number, and email address;</li>
         <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
         <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf.</li>
      </ol>
   </li>
</ul>

<p>WWF&rsquo;s agent for notice of claims of copyright or other intellectual property infringement can be reached either by mail to Copyright Agent, c/o General Counsel, World Wildlife Fund, Inc., 1250 24th Street, N.W., Washington, DC, 20037; or by email to copyrightagent@wwfus.org. This contact information is only for suspected copyright or other intellectual property infringement notices only, and is not for reprint or use permission requests. Contact information for other matters is provided elsewhere on the Site. We may give notice of a claim of copyright infringement to our users by means of a general notice on the Site or in the Tool, electronic mail to a user's email address in our records, or by written communication.</p>

<ul>
   <li>
      <strong>Data Sharing. </strong>WWF offers two privacy options with respect to the content you upload to the Site or the Tool.
      <ul>
         <li><em>Private</em>. Assessment results (quantitative and qualitative answers) are private as well as the information provided in the Background Information box including, name of facilitator, site location, name of MA, management and governance type and method of assessment, are private.</li>
         <li>Assessment results (quantitative and qualitative answers) are public as well as information provided in the Background Information box including, name of facilitator, site location, name of MA, and management and governance type and method of assessment. Additional data uploaded such as management plans and geospatial files to facilitate knowledge management are also public. <br /> In order to maintain transparency as to who collected the original data, data is always associated with the names of, and a mechanism to contact, project administrators (but email addresses are never public)</li>
      </ul>
   </li>
</ul>
<ul>
   <li><strong>Warranty and Disclaimers.</strong> The Tool and the Site are being provided by WWF under this Agreement solely for educational purposes and in furtherance of WWF&rsquo;s exempt mission. The Tool, the Site, and all materials, content, data, and other information contained therein are provided strictly on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis without warranty of any kind, either express, implied, statutory or otherwise, including, but not limited to, the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose. To the maximum extent permitted by law, WWF will have no liability related to any content arising under intellectual property rights, libel, privacy, publicity, obscenity or other laws. WWF also disclaims all liability with respect to the misuse, loss, modification, or unavailability of any data. WWF does not warrant that the Tool or the Site will meet your requirements; that the Tool or the Site will be uninterrupted, timely, secure, or error-free; that the information provided through the Tool or the Site is accurate, reliable or correct; that any defects or errors will be corrected; that the Tool or the Site will be available at any particular time or location; or that the Tool or the Site are free of viruses or other harmful components. WWF makes no representation that the Tool or the Site are appropriate or available for use at all locations, and access to the service from territories where the service is illegal is prohibited.<br /> </li>
   <li>
      <strong>Limitation of Liability</strong>. In no event shall WWF, or any of its directors, trustees, officers, employees, independent contractors, or agents of any operator entity be liable to you or any third party for any special, punitive, incidental, indirect or consequential damages or losses of any kind, or any damages or losses whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or if service provider has been advised of the possibility of such damages or losses, and on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with:
      <ul>
         <li>The access or use of or the inability to access or use the Tool or the Site;</li>
         <li>the statements or actions of any third party on or via the Tool or the Site;</li>
         <li>any unauthorized access to or alteration of the Tool or the Site;</li>
         <li>any information that is sent or received or not sent or received;</li>
         <li>any failure to store or loss of data or other content; and</li>
         <li>any delayed or interrupted access to the Site or the Tool.<br /> </li>
      </ul>
   </li>
   <li><strong>Release and Indemnification. </strong>You hereby agree to release WWF from any and all claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with your access to or use of the Tool or the Site. To the fullest extent permitted by law, you agree to indemnify, defend and hold WWF and any and all of its directors, trustees, officers, employees, independent contractors and agents of the service provider entity harmless from any and all third-party claims, including reasonable attorneys&rsquo; fees, due to or arising from: (a) your access to or use of the Tool or the Site; (b) your violation of any provision of this Agreement; (c) content that you may submit, post to or transmit to the Tool or the Site (including a third party&rsquo;s use of such content (e.g. reliance on the accuracy, completeness or usefulness of your data)); (d) content that you may access or use using the Tool or the Site, including your reliance on the accuracy, completeness or usefulness of any data; or (d) your infringement of any third party&rsquo;s copyright, trademark, or other proprietary right, violation of privacy right or publicity right, and libel or violation of any other law in connection with this Agreement.</li>
</ul>

<ul>
   <li><strong>General.</strong>
      <ul>
         <li><strong>Choice of Law. </strong>Except to the extent applicable law provides otherwise, this Agreement and any access to or use of the Tool and/or the Site are governed by the laws of the District of Columbia, USA. You agree and hereby submit to the exclusive personal jurisdiction and venue of the courts located in the District of Columbia. Notwithstanding the foregoing, WWF reserves the right to seek equitable or injunctive relief in any jurisdiction in the world.</li>
         <li>The provisions of this Agreement that by their nature should survive termination will survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</li>
         <li>To the fullest extent permitted by law, you (1) consent to receive communications from WWF in an electronic form via the email address you have submitted or via the Tool or the Site; and (2) agree that all Terms of Use, agreements, notices, disclosures, and other communications that WWF provides to you electronically satisfy any legal requirement that those communications would satisfy if they were on paper. Legal notice to WWF must be made in writing to the address provided below.</li>
         <li>WWF may, in its sole discretion, modify all or any portions of this Agreement at any time. WWF will notify you of any changes by posting notice of such modifications in the Tool or the Site, by sending notice via e-mail, or other means, in WWF&rsquo;s discretion. Your continued use of the Tool and/or the Site following notice of such modifications shall be deemed to be your acceptance of any such modifications to the Agreement.</li>
         <li><strong>Termination of Service or Access</strong>. WWF reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Tool and/or the Site, in whole or in part, or your access thereto, with or without notice. You may terminate your access to the Tool/the Site at any time by following the process set out in the Tool/the Site or contacting WWF. You will have the choice to remove or retain any data that you have uploaded following termination of your account.&nbsp; Upon termination, any licenses, rights or permissions granted to you hereunder shall terminate immediately.</li>
         <li><strong>No Assignment.</strong> You may not assign or delegate any rights or obligations hereunder without WWF&rsquo;s prior written consent, and any unauthorized assignment and delegation by you shall be null and void.</li>
         <li><strong>Severability, No Waiver, and Survival. </strong>If any part of this Agreement is held invalid or unenforceable, that portion of the Agreement will be construed to reflect the parties original intent. The remaining portions will remain in full force and effect. Any failure on the part of WWF to enforce any provision of this Agreement will not be considered a waiver of WWF's right to enforce such provision. WWF&rsquo;s rights under this Agreement will survive any termination or expiration of this Agreement.</li>
         <li>Section headings within this Agreement are for convenience only.</li>
         <li><strong>Entire Agreement.</strong> This Agreement constitutes the entire agreement between you and WWF relating to the subject matter and supersedes all prior or contemporaneous understandings, communications or agreements, written or oral, regarding such subject matter.</li>
         <li>If you have questions about this Agreement, please contact help@elinordata.org. Direct legal notices to: World Wildlife Fund, 1250 24th Street, N.W.Washington, DC 20037.</li>
      </ul>
   </li>
</ul>

`;
