export default `
<p>Ireto Fepetra Fampiasana ireto dia mihatra manokana amin'ny fidirana sy fampiasana ny Fitaovana Fitantanana sy Fitantanana Elinor sy ny angona rehetra ambany, tranokala mifandraika, serivisy an-tserasera, ary fampiharana finday (fiaraha-milaza, ny &ldquo;Fitaovana&rdquo; na &ldquo;Elinor&rdquo;) izay atolotry ny World Wildlife Fund, Inc. (&ldquo;WWF&rdquo;) amin'ny alalan'ny tranokala <a href="https://elinordata.org">elinordata.org</a> (ny &ldquo;Tranokala&rdquo;). Amin'ny fidirana na fampiasana ny Fitaovana sy/na ny Tranokala, dia manaiky ny fehezin'ireto Fepetra Fampiasana ireto ianao ary manaiky fa ireto Fepetra Fampiasana ireto dia tsy manova amin'ny fomba rehetra ny fepetra na fepetra amin'ny fifanarahana hafa mety ananao amin'ny WWF. Raha mampiasa ny Fitaovana na ny Tranokala ianao ho an'ny orinasa iray, dia manambara sy manome toky ianao fa nahazo alalana hanaiky ireto Fepetra Fampiasana ireto amin'ny anaran'ny orinasa izany, ary ny orinasa izany dia manaiky ny hanome onitra ny WWF noho ny fanitsakitsahana ireto Fepetra Fampiasana ireto.</p>
<p>Ny WWF dia mitana ny zo hanova na hanova izay fepetra sy fepetra rehetra ao anatin'ireto Fepetra Fampiasana ireto amin'ny fotoana rehetra ary amin'ny fahefana tokana. Ny fanovana na fanovana rehetra dia hanan-kery avy hatrany rehefa avy namoaka ny fanitsiana eo amin'ny Tranokala. Ny fampiasana ny Fitaovana hatrany aorian'ny namoahana ny fanovana na fanovana dia ho fanekena ny fanovana na fanovana toy izany. Noho izany, tokony hijery matetika ireo Fepetra Fampiasana sy politika mifandraika ianao rehefa mandeha ny fotoana mba hahatakatra ireo fepetra sy fepetra mihatra amin'ny fampiasana ny Fitaovana. Raha tsy manaiky ny fepetra novaina ianao, dia tokony hitsahatra tsy hampiasa ny Fitaovana.</p>
<p>Ireto ny Fepetra Fampiasana mihatra amin'ny Fitaovana:</p>
<ul>
   <li><strong>Fampiasana.</strong>Manaiky ianao hampiasa ny Fitaovana, na &ldquo;Elinor&rdquo; sy ny vokatra rehetra novokarina tamin'ny fampiasana angona avy amin'ny Elinor mba handroso ny tanjona fiarovana. Manaiky ianao hanatanteraka ny Fitaovana sy ny Tranokala amin'ny fomba mifandrindra amin'ny lalàna, fitsipika, sata ary fitsipika mihatra amin'ny fotoana rehetra. Manaiky ianao ary manaiky fa ianao irery no tompon'andraikitra amin'ny fanatanterahana toy izany ary manaiky hanome onitra ny WWF sy ny mpitantana, afisera, mpiasa, mpisolo tena, ary mpiara-miasa amin'ny tranga rehetra mitranga amin'ny fanitsakitsahana ny adidy fanajana. Fanampiny ianao dia manaiky tsy hampiasa ny Fitaovana na ny Tranokala amin'ny fomba rehetra hanalam-baraka, hanenjika na handrahona olona na orinasa, na hampiditra na hahatonga ho azo izay fitaovana tsy mendrika, pornografika na manafintohina, niniana hamitaka, mandranjanana na manafintohina olona na vondrona, manitsakitsaka lalàna mihatra na mampiroborobo fanitsakitsahana toy izany, ahitana na hampiditra malware, virus na singa manimba, na manitsakitsaka ny zo manokana na tsy miankina amin'ny antoko fahatelo. Na dia mety hanesotra hevitra ny WWF amin'ny fahefana tokana izay heveriny fa manitsakitsaka ny lalàna na ny politika WWF aza, dia tsy manao fanehoana ny WWF momba ny fanitsiana ary tsy manolo-tena hijery ny atiny rehetra nalefa amin'ny sehatra<br /> </li>
   <li><strong>Kaonty; Fampahalalana Manokana; Fifehezana ny Fampahalalanao. </strong>Raha te hampiditra hevitra amin'i Elinor ianao, dia tsy maintsy misoratra anarana aloha amin'ny alalan'ny Tranokala. Ny fisoratana anarana dia mitaky famoronana login voaro amin'ny teny miafina sy fanomezana fampahalalana manokana kely, ao anatin'izany ny anaranao sy ny adiresy mailaka. Tompon'andraikitra amin'ny fiarovana ny login sy teny miafinao ianao, ary ho an'ny atiny rehetra nomena, profil noforonina, fanombanana natao ary hetsika hafa rehetra mitranga eo ambany izany. Hampandre ny WWF avy hatrany ianao raha lasa fantatra ny fampiasana tsy nahazoana alalana na ny fidirana ny Serivisy. Tsy hampiasa ny fampahalalana manokana nomenao izahay amin'ny tanjona hafa ankoatra ny fitantanana ny kaonty Tranokala sy hifandraisana aminao momba ny fiovana lehibe na fanelingelenana amin'ny sehatra. Manana zo hangataka fampahalalana manokana rehetra nangonina amin'ny fampiasana ny Fitaovana sy ny Tranokala ianao mba hovana na hofafana any aoriana <strong>Raha manana fanontaniana momba ny fampahalalana manokana nangonina ianao, ao anatin'izany ny fangatahana hofafana, azafady mifandraisa amin'ny help@elinordata.org.</strong> Na dia tsy hanambara ny fampahalalana manokanao amin'ny antoko fahatelo afa-tsy ho an'ny tanjona hanampy amin'ny fitantanana ny Fitaovana sy ny Tranokala aza ny WWF, raha mponina any California ianao, ny California Civil Code Fizarana 1798.83 dia mamela anao hangataka fampahalalana momba ny fanambaran'ny fampahalalana manokana ho an'ireo antoko fahatelo ho an'ny tanjona marketing mivantana azy ireo.<strong> Mba hanaovana fangatahana toy izany, azafady mifandraisa amin'ny help@elinordata.org.</strong> Mariho fa ny WWF dia tsy afaka hanatanteraka foana ny fangatahana hamafa raha tsy azony atao ara-dalàna hafa, fa ny fikambanana, araka izay azo atao, dia hampandre anao ireo teritery toy izany ho valin'ny fangatahana nataonao.</li>
   <li><strong>Copyright sy Lisansa voafetra.</strong> Raha tsy voaambara hafa ao amin'ny Fitaovana sy/na ny Tranokala, ny Fitaovana, ny Tranokala, ary ny atiny rehetra sy fitaovana hafa ao anatin'izany, ao anatin'izany, tsy voafetra, ny marika ara-barotra rehetra, marika serivisy, endrika, soratra, sary, sary, fampahalalana, angona, rindrambaiko, fomba, famoronana, rakitra feo, rakitra hafa ary ny safidy sy ny filaharana amin'izany dia fananana manokana an'ny WWF ary arovan'ny lalàna momba ny copyright, marika ara-barotra sy hafa momba ny fananana ara-tsaina eto Etazonia sy iraisam-pirenena. Nomena fahazoan-dalana miditra sy mampiasa ny Fitaovana sy ny Tranokala ho an'ny tanjona tsy ara-barotra voalaza etsy ambony sy araka ireto Fepetra Fampiasana ireto. Ny fampiasana avy aminao ny anarana Elinor, logo na marika hafa rehetra dia ho eo ambany fanekena mialoha an-tsoratra avy amin'ny WWF. Manaiky mazava ianao fa ny fahazoan-dalana hampiasa ny Fitaovana/Tranokala dia tsy ahitana: (a) ny fampiasana ara-barotra na famerenana na famerenana ny Fitaovana na ny Tranokala; (b) ny fanangonana sy fampiasana ny lisitry ny vokatra, sary na famaritana; (c) ny fizarana, fampisehoana ampahibemaso na fampisehoana ampahibemaso ny fitaovana ao anatin'ny Fitaovana na ny Tranokala, (d) ny fanaovana fampiasana derivative amin'ny Fitaovana na ny Tranokala, na ampahany amin'izany; (e) ny fampiasana angon-drakitra mining, robot na fomba fanangonana na fitrandrahana angona mitovy; (f) ny fampidinana (ankoatra ny pejy caching na toy izay azo atao hafa) ny ampahany amin'ny Fitaovana na ny Tranokala; na (g) ny fampiasana rehetra amin'ny Fitaovana na ny Tranokala ankoatra ny tanjona natao azy. Ny fahazoan-dalana nomena eto dia azon'ny WWF avy hatrany, miaraka na tsy misy antony. Afa-tsy voalaza mazava eto, ny Fitaovana, ny Tranokala, ary ny fitaovana ambanin'izany dia tsy azo kopiana, averina, zarainy, navoaka indray, nalaina, naseho, napetraka, nalefa na ampiasaina amin'ny fomba na fomba rehetra, ao anatin'izany, fa tsy voafetra, elektronika, mekanika, photocopying, firaketana, na hafa, tsy misy fahazoan-dalana mialoha an-tsoratra avy amin'ny WWF na ny tompon'ny copyright. Ny fahazoan-dalana nomena anao dia tapitra avy hatrany raha manitsakitsaka ny Fepetra Fampiasana rehetra ianao. Aorian'ny famarana, dia tsy maintsy manimba avy hatrany ny fitaovana nalaina sy natonta ianao. Ianao koa dia tsy afaka, tsy misy fahazoan-dalana avy amin'ny WWF, "mitaratra" ny fitaovana rehetra ao anatin'ny Fitaovana na ny Tranokala amin'ny mpizara hafa. Ny fampiasana tsy nahazo alalana ny fitaovana rehetra ao anatin'ny Fitaovana na ny Tranokala dia mety hanitsakitsaka ny lalàna mihatra (ao anatin'izany ny lalàna copyright, lalàna momba ny marika ara-barotra, lalàna momba ny fiainana manokana sy fampahalalam-baovao, ary fitsipika sy sata momba ny fifandraisana).
    </li>
   <li><strong>Atiny Mpampiasa. </strong>Manambara sy manome toky ianao fa manana ny atiny rehetra (ao anatin'izany ny angona nomena tamin'ny fanombanana) ianao nalefa, nomena, na nataona ho azo amin'ny Fitaovana na ny Tranokala, ary/na manana ny zo rehetra amin'ny atiny ilaina hanaiky an'ity Fifanarahana ity, ary tsy misy ampahany amin'ny atiny no hanitsakitsaka na hanitsakitsaka ny copyright, tsiambaratelo ara-barotra, marika ara-barotra, patanty, famoronana, na zo manokana na manokana hafa amin'ny antoko fahatelo. Manambara sy manome toky ianao fa toy izany atiny izany dia ho marina, marina, ary feno araka ny fahalalanao. Ianao irery no tompon'andraikitra amin'ny atinao rehetra. Ianao dia manome zo tsy tapaka, tsy misy royalty, tsy miavaka, tsy azo ovaina, manerantany, fa tsy ny adidy, hampiasa, hizara, handika ary hitahiry ny atinao mandrakizay. Ny atiny izay anananao sy nalefa dia mbola ho fanananao ary tsy hozaraina na havotsotra amin'ny WWF raha tsy misy fahazoan-dalana mazava avy aminao, afa-tsy ny WWF dia mety hizara ny atinao amin'ny fomba aggregate/anonymized na toy izay azo atao eo ambany ny famehana Data Sharing etsy ambany. Mariho anefa fa tsy afaka hanatanteraka foana izahay ny fangatahana hofafana ho an'ny antony ara-dalàna manokana izay hampandrenesana anao, raha misy, amin'ny fotoana hataonao fangatahana. Ny fangatahana hamafa angona tsy hita ho an'ny olona dia tsy maintsy atao an-tsoratra amin'ny mpandraharaha.</li>
   <li><strong>Tranokala Mifandray avy amin'ny Tranokala. </strong>Ny Fitaovana sy/na ny Tranokala dia mety ahitana rohy na mety hanisy frame tranokala antoko fahatelo ("Tranokala Antoko Fahatelo") ary mety ahitana na mifandray amin'ny fampahalalana antoko fahatelo, fitaovana, fifandraisana na atiny hafa (fiaraha-milaza ny "Atiny Antoko Fahatelo"). Toy izany Atiny Antoko Fahatelo sy Tranokala Antoko Fahatelo dia tsy eo ambany fahefana WWF, ary ny WWF dia tsy manohana, mandray andraikitra na andraikitra, na manao fanehoana na fiantohana momba ny, Tranokala Antoko Fahatelo, ny Atiny Antoko Fahatelo na vokatra na serivisy rehetra atolotry ny antoko fahatelo eo amin'ny Tranokala na Tranokala Antoko Fahatelo. Ny WWF dia tsy mikasa rohy amin'ity Tranokala ity ho fanondroana na fanohanana ny orinasa mifandray, na ny vokatra na serivisy azy ireo, ary nomena ho an'ny fahazoana aina fotsiny. Ny fampiasana ny Tranokala Antoko Fahatelo na Atiny Antoko Fahatelo, na vokatra sy serivisy antoko fahatelo, dia amin'ny mety hisian'ny loza sy fepetra sy fepetra na ny mpamatsy.<br /> </li>
   <li>
      <strong>Fitarainana Copyright.</strong> Raha mino amin'ny finoana tsara ianao fa ny asa misy ny zo rehetra nataonao dia namerina novokarina tao amin'ny tranokala nay tsy nahazo alalana amin'ny fomba izay mamorona fanitsakitsahana copyright, azafady omeo ny mpisolo tena copyright an'ny WWF, amin'ny adiresy nomena etsy ambany, ny fampahalalana manaraka:
      <ol>
         <li>sonia elektronika na ara-batana amin'ny olona nahazo fahefana hiasa amin'ny anaran'ny tompon'ny copyright na tombontsoa ara-tsaina hafa;</li>
         <li>famaritana ny asa misy ny zo rehetra na fananana ara-tsaina hafa izay lazainao fa voasakana;</li>
         <li>famaritana izay misy ny fitaovana izay lazainao fa manafoana dia misy amin'ity tranokala ity;</li>
         <li>ny adiresinao, laharana telefaona, ary adiresy mailaka;</li>
         <li>fanambarana nataonao fa manana finoana tsara ianao fa ny fampiasana nifandirana dia tsy nahazo fahazoan-dalana avy amin'ny tompon'ny zo rehetra, ny mpisolo tena, na ny lalàna; ary</li>
         <li>fanambarana nataonao, natao eo ambany sazy amin'ny fanaovana fianianana tsy marina, fa ny fampahalalana etsy ambony ao amin'ny fampandrenesana dia marina ary fa ianao no tompon'ny zo rehetra na fananana ara-tsaina na nahazo alalana hiasa amin'ny anaran'ny tompon'ny zo rehetra na fananana ara-tsaina.</li>
      </ol>
   </li>
</ul>

<p>Ny mpisolo tena WWF ho an'ny fampandrenesana momba ny fitarainana copyright na fanitsakitsahana fananana ara-tsaina hafa dia azo tontosaina amin'ny alalan'ny mailaka any amin'ny Copyright Agent, c/o General Counsel, World Wildlife Fund, Inc., 1250 24th Street, N.W., Washington, DC, 20037; na amin'ny alalan'ny mailaka any amin'ny copyrightagent@wwfus.org. Ity fampahalalana fifandraisana ity dia ho an'ny fampandrenesana momba ny copyright na fanitsakitsahana fananana ara-tsaina hafa ihany, ary tsy ho an'ny fangatahana reprint na fahazoan-dalana fampiasana. Fampahalalana fifandraisana ho an'ny raharaha hafa dia nomena any amin'ny toerana hafa ao amin'ny Tranokala. Mety hanome fampandrenesana momba ny fitarainana fanitsakitsahana copyright izahay amin'ny mpampiasa anay amin'ny alalan'ny fampandrenesana ankapobeny eo amin'ny Tranokala na ao amin'ny Fitaovana, mailaka elektronika amin'ny adiresy mailaka mpampiasa ao amin'ny firaketana anay, na amin'ny fifandraisana an-tsoratra.</p>

<ul>
   <li>
      <strong>Fizarana Angona. </strong>Ny WWF dia manolotra safidy tsiambaratelo roa momba ny atiny nalefanao amin'ny Tranokala na ny Fitaovana.
      <ul>
         <li><em>Manokana</em>. Valim-panombanana (valin-tsaina ary kalitao) dia manokana ary koa ny fampahalalana nomena ao amin'ny boaty Fampahalalana Background ao anatin'izany, anarana mpandrindra, toerana toerana, anaran'ny MA, karazana fitantanana sy fitantanana ary fomba fanombanana, dia manokana.</li>
         <li>Valim-panombanana (valin-tsaina ary kalitao) dia ho an'ny daholobe ary koa fampahalalana nomena ao amin'ny boaty Fampahalalana Background ao anatin'izany, anarana mpandrindra, toerana toerana, anaran'ny MA, ary karazana fitantanana sy fitantanana ary fomba fanombanana. Angona fanampiny nalefa toy ny drafitra fitantanana sy rakitra geospatial mba hanamora ny fitantanana fahalalana dia ho an'ny daholobe koa. <br /> Mba hitazomana ny transparence momba ny nahangonana ny angona tany am-boalohany, ny angona dia mifandray foana amin'ny anarana, ary fomba hifandraisana, ny mpitantana tetikasa (fa ny adiresy mailaka dia tsy ho an'ny daholobe mihitsy)</li>
      </ul>
   </li>
   <li><strong>Fiantohana sy Fanilihana.</strong> Ny Fitaovana sy ny Tranokala dia atolotry ny WWF eo ambany ity Fifanarahana ity ho an'ny tanjona fanabeazana fotsiny ary ho fampandrosoana ny iraka fanafahana WWF. Ny Fitaovana, ny Tranokala, ary ny fitaovana rehetra, atiny, angona, ary fampahalalana hafa ao anatin'izany dia omena amin'ny fomba &ldquo;toy izany&rdquo; ary &ldquo;toy izany misy&rdquo; tsy misy fiantohana karazana, na mazava, na implied, ara-dalàna na hafa, ao anatin'izany, fa tsy voafetra, ny fiantohana implied momba ny lohateny, tsy fanitsakitsahana, ara-barotra na fahazoana ho an'ny tanjona manokana. Hatramin'ny fetra azon'ny lalàna atao, ny WWF dia tsy hanana andraikitra mifandraika amin'ny atiny mipoitra eo ambany zo ara-tsaina, libel, fiainana manokana, fampahalalam-baovao, tsy mendrika na lalàna hafa. Ny WWF koa dia manilika ny andraikitra rehetra momba ny fampiasana diso, fahaverezan'ny, fanovana, na tsy fisian'ny angona. Ny WWF dia tsy manome toky fa ny Fitaovana na ny Tranokala dia hifanentana amin'ny fepetra; fa ny Fitaovana na ny Tranokala dia tsy hisy fanelingelenana, amin'ny fotoana, azo antoka, na tsy misy hadisoana; fa ny fampahalalana nomena amin'ny alalan'ny Fitaovana na ny Tranokala dia marina, azo itokiana na marina; fa ny lesoka na hadisoana rehetra dia hohitsy; fa ny Fitaovana na ny Tranokala dia ho azo amin'ny fotoana na toerana manokana; na fa ny Fitaovana na ny Tranokala dia tsy misy virus na singa manimba hafa. Ny WWF dia tsy manao fanehoana fa ny Fitaovana na ny Tranokala dia mety na azo ampiasaina amin'ny toerana rehetra, ary ny fidirana ny serivisy avy amin'ny faritany izay tsy ara-dalàna ny serivisy dia voarara.<br /> </li>
   <li>
      <strong>Fetra ny Andraikitra</strong>. Amin'ny toe-javatra rehetra, ny WWF, na ny mpitantana, mpitantana, afisera, mpiasa, mpikambana tsy miankina, na mpisolo tena amin'ny orinasa mpandraharaha rehetra dia tsy ho tompon'andraikitra aminao na antoko fahatelo momba ny fahasimbana na fitateran-doza manokana, sazy, tsy nahy, tsy mivantana na vokatry na fahaverezan'ny karazana, na fahasimbana na fahaverezan'ny rehetra, ao anatin'izany ireo vokatr'ny fahaverezan'ny fampiasana, angona na tombony, na nahy na tsia na raha ny mpamatsy serivisy dia nampandrenesina ny mety hisian'ny fahasimbana na fahaverezana toy izany, ary amin'ny teoria rehetra momba ny andraikitra, ao anatin'izany ny fanitsakitsahana fifanarahana na fiantohana, tsy fikarakarana na hetsika tsy marina hafa, na fitarainana hafa mipoitra avy na mifandray amin'ny:
      <ul>
         <li>Ny fidirana na fampiasana na ny tsy fahafahana miditra na mampiasa ny Fitaovana na ny Tranokala;</li>
         <li>ny fanambarana na hetsika amin'ny antoko fahatelo eo amin'ny na amin'ny alalan'ny Fitaovana na ny Tranokala;</li>
         <li>ny fidirana tsy nahazo alalana na fanovana ny Fitaovana na ny Tranokala;</li>
         <li>ny fampahalalana izay nalefa na nalefa na tsy nalefa na nalefa;</li>
         <li>ny tsy fahampiana hitahiry na fahaverezan'ny angona na atiny hafa; ary</li>
         <li>ny fidirana nahemotra na nanelingelina ny Tranokala na ny Fitaovana.<br /> </li>
      </ul>
   </li>
   <li><strong>Famotsoran-dalana sy Fanomezam-pialoha. </strong>Ianao dia manaiky hamoaka ny WWF avy amin'ny fitarainana rehetra, fangatahana ary fahasimbana (marina sy vokany) amin'ny karazana rehetra sy natiora, fantatra sy tsy fantatra, mipoitra avy na mifandray amin'ny fidirana na fampiasana ny Fitaovana na ny Tranokala. Hatramin'ny fetra azon'ny lalàna atao, manaiky ianao hanome onitra, hiaro ary hitahiry ny WWF sy ny mpitantana rehetra, mpitantana, afisera, mpiasa, mpikambana tsy miankina ary mpisolo tena amin'ny orinasa mpamatsy serivisy tsy misy fahasimbana avy amin'ny fitarainana antoko fahatelo rehetra, ao anatin'izany ny saram-pitsarana mitombina, noho na mipoitra avy amin'ny: (a) ny fidirana na fampiasana ny Fitaovana na ny Tranokala; (b) ny fanitsakitsahana ny fepetra rehetra amin'ity Fifanarahana ity; (c) atiny mety homenao, hapetraka na halefa amin'ny Fitaovana na ny Tranokala (ao anatin'izany ny fampiasan'ny antoko fahatelo io atiny io (ohatra: fiankinana amin'ny fahamarinan-tsaina, fahafenoana na fahamendrehana amin'ny angonanao)); (d) atiny mety ho azonao na ampiasainao amin'ny fampiasana ny Fitaovana na ny Tranokala, ao anatin'izany ny fiankinana amin'ny fahamarinan-tsaina, fahafenoana na fahamendrehana amin'ny angona; na (d) ny fanitsakitsahana ny copyright, marika ara-barotra, na zo manokana hafa amin'ny antoko fahatelo, fanitsakitsahana ny zo tsiambaratelo na zo fampahalalam-baovao, ary libel na fanitsakitsahana lalàna hafa mifandray amin'ity Fifanarahana ity.</li>
   <li><strong>Ankapobeny.</strong>
      <ul>
         <li><strong>Safidy Lalàna. </strong>Afa-tsy raha manome hafa ny lalàna mihatra, ity Fifanarahana ity sy ny fidirana na fampiasana ny Fitaovana sy/na ny Tranokala dia fehezin'ny lalànan'ny District of Columbia, USA. Manaiky ianao ary manolotra eto amin'ny fahefana manokana sy toerana amin'ny fitsarana any amin'ny District of Columbia. Na eo aza izany, ny WWF dia mitana ny zo hitady fanomezam-pialoha equity na injunctive amin'ny fahefana rehetra eran-tany.</li>
         <li>Ny fepetra amin'ity Fifanarahana ity izay tokony ho velona aorian'ny famarana dia ho velona, ao anatin'izany, tsy voafetra, fepetra momba ny fananana, fanilihana fiantohana, fanomezam-pialoha, ary fetra momba ny andraikitra.</li>
         <li>Hatramin'ny fetra azon'ny lalàna atao, ianao (1) manaiky handray fifandraisana avy amin'ny WWF amin'ny endrika elektronika amin'ny alalan'ny adiresy mailaka natolotrao na amin'ny alalan'ny Fitaovana na ny Tranokala; ary (2) manaiky fa ny Fepetra Fampiasana rehetra, fifanarahana, fampandrenesana, fanambaram-baovao, ary fifandraisana hafa atolotry ny WWF anao amin'ny elektronika dia mahafa-po izay fepetra ara-dalàna izay toy izany fifandraisana izany dia mahafa-po raha teo amin'ny taratasy. Fampandrenesana ara-dalàna amin'ny WWF dia tsy maintsy atao an-tsoratra amin'ny adiresy nomena etsy ambany.</li>
         <li>Ny WWF dia mety, amin'ny fahefana tokana, hanova ny rehetra na ampahany amin'ity Fifanarahana ity amin'ny fotoana rehetra. Ny WWF dia hampandre anao momba ny fanovana rehetra amin'ny alalan'ny fampandrenesana momba ny fanovana toy izany ao amin'ny Fitaovana na ny Tranokala, amin'ny fandefasana fampandrenesana amin'ny alalan'ny e-mail, na fomba hafa, amin'ny fahefana WWF. Ny fampiasana ny Fitaovana sy/na ny Tranokala hatrany aorian'ny fampandrenesana momba ny fanovana toy izany dia heverina ho fanekena izay fanovana amin'ny Fifanarahana.</li>
         <li><strong>Famarana ny Serivisy na Fidirana</strong>. Ny WWF dia mitana ny zo amin'ny fotoana rehetra sy avy amin'ny fotoana hatramin'ny fotoana hanova na hitsahatra, vonjimaika na mandrakizay, ny Fitaovana sy/na ny Tranokala, amin'ny ankapobeny na amin'ny ampahany, na ny fidirana azy, miaraka na tsy misy fampandrenesana. Azonao atao ny mamarana ny fidirana ny Fitaovana/ny Tranokala amin'ny fotoana rehetra amin'ny fanarahana ny fizotran-tsipika apetraka ao amin'ny Fitaovana/ny Tranokala na mifandray amin'ny WWF. Hanana safidy hanesotra na hitahiry ny angona rehetra nalefa aorian'ny famarana ny kaontinao ianao. Aorian'ny famarana, ny lisansa, zo na fahazoan-dalana nomena anao eto dia tapitra avy hatrany.</li>
         <li><strong>Tsy Fahazoan-dalana.</strong> Tsy afaka manome na mandefa zo na andraikitra eto ianao raha tsy misy fanekena mialoha an-tsoratra avy amin'ny WWF, ary ny fanomezana sy fandefasana tsy nahazo alalana nataonao dia tsy manan-kery.</li>
         <li><strong>Fanasarahana, Tsy Fandaozana, ary Fahavelomana. </strong>Raha ampahany amin'ity Fifanarahana ity no heverina ho tsy manan-kery na tsy azo ampiharina, io ampahany io amin'ny Fifanarahana dia hadika mba hanehoana ny fikasana tany am-boalohany. Ny ampahany sisa dia hijanona amin'ny hery sy fiantraikany feno. Ny tsy fahampian'ny WWF hampihatra ny fepetra rehetra amin'ity Fifanarahana ity dia tsy heverina ho fanilihana ny zo WWF hampihatra io fepetra io. Ny zon'ny WWF eo ambany ity Fifanarahana ity dia ho velona amin'ny famarana na fahataperan'ny ity Fifanarahana ity.</li>
         <li>Ny lohateny fizarana ao anatin'ity Fifanarahana ity dia ho an'ny fahazoana aina fotsiny.</li>
         <li><strong>Fifanarahana Manontolo.</strong> Ity Fifanarahana ity dia mandrafitra ny fifanarahana manontolo eo aminao sy ny WWF momba ny lohahevitra ary manolo ireo fifanarahana, fifandraisana na fifanarahana taloha na mifanerana, an-tsoratra na am-bava, momba ny lohahevitra toy izany.</li>
         <li>Raha manana fanontaniana momba ity Fifanarahana ity ianao, azafady mifandraisa amin'ny help@elinordata.org. Fampandrenesana ara-dalàna mivantana amin'ny: World Wildlife Fund, 1250 24th Street, N.W.Washington, DC 20037.</li>
      </ul>
   </li>
</ul>

`;
