name: Deploy prod app to AWS S3
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-20.04
        environment: prod
        steps:
            -   uses: actions/checkout@v2
            -   name: Configure AWS Credentials for S3
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   uses: actions/setup-node@v2
                with:
                    node-version: 16
            -   name: Install package.json dependencies
                run: yarn install
            -   name: Nuxt build
                run: yarn build
                env:
                    BASE_URL: ${{ vars.BASE_URL }}
                    BASE_URL_API: ${{ vars.BASE_URL_API }}
            -   name: Nuxt generate
                run: yarn generate
                env:
                    BASE_URL: ${{ vars.BASE_URL }}
                    BASE_URL_API: ${{ vars.BASE_URL_API }}
            -   name: Deploy static site to S3 bucket
                run: aws s3 sync ./dist/ ${{ secrets.AWS_S3_PROD_BUCKET_NAME }} --delete
            -   name: Configure AWS Credentials for Cloudfront
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_CLOUDFRONT_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_CLOUDFRONT_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}
            -   name: Invalidate cloudfront
                run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_PROD_DISTRIBUTION_ID }} --paths "/"
